server:
  port: 8089

spring:
  #  datasource: # mysql数据库连接
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:mysql://8.130.78.60:3306/microServices
  #    username: java
  #    password: 12345678
  main:
    web-application-type: reactive

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #mybatis日志
  mapper-locations: classpath:mapper/*.xml

