server:
  port: 8080

spring:
#  application:
#    name: nacos-consumer
  datasource: # mysql数据库连接
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.130.78.60:3306/microServices
    username: java
    password: 12345678
  cloud:
    nacos:
      discovery:
        server-addr: 8.130.77.190:8848
  main:
    web-application-type: reactive

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #mybatis日志
  mapper-locations: classpath:mapper/*.xml

#消费者将要去访问的微服务名称(注册成功进nacos的微服务提供者，注意这个是自定义的配置)
#service-url:
#  nacos-user-service: http://nacos-payment-provider